site_name: Raka Project
theme:
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
  features:
    - content.code.copy
    - navigation.footer
    - Copyright &copy; 2016 - 2020 Martin Donath
  name: material
  logo:
  language: en

markdown_extensions:
  - attr_list
  - tables